---
- name: update homebrew & upgrade packages
  homebrew:
    update_homebrew: yes
    upgrade_all: yes

- name: update homebrew packages
  homebrew:
    name: ['node', 'git-flow', 'maven', 'angular-cli', 'typescript']
    state: latest
    install_options: force

- name: update homebrew cask packages
  homebrew_cask:
    name: "{{ item }}"
    state: upgraded
    install_options: upgrade
  with_items:
    - "visual-studio-code"
    - "postman"
    - "vlc"
    - "google-chrome"
    - "gimp"
    - "studio-3t"
    - "skype"
    - "expressvpn"
    - "spectacle"
    - "iterm2"
    - "intellij-idea-ce"
    - "whatsapp"
    - "telegram"

- name: check oh-my-zsh installation
  command: test -d ~/.oh-my-zsh
  ignore_errors: true
  register: omz_bound

- name: update oh-my-zsh
  git: 
    repo: https://github.com/robbyrussell/oh-my-zsh.git
    dest: ~/.oh-my-zsh
    update: yes
    force: yes
    # accept_hostkey: yes
  when: omz_bound is succeeded
