---
- name: print out the hostname of target
  command: hostname

- name: switch shell
  shell: echo "$0"
  args:
    executable: /bin/bash

- name: check npm version
  command: npm -v
#   register: npm_version_output
# - name: display npm version output
#   debug: 
#     var: npm_version_output.stdout_lines

# - name: update npm
#   npm: 
#     name: npm
#     global: yes
#     state: latest
#   register: npm_install_output
# - name: display npm install output
#   debug:
#       msg: "{{ npm_install_output.stdout_lines }}"

- name: "update npm packages"
  npm: 
    name: "{{ item }}"
    global: yes
    state: latest
  with_items:
    - "npm"
    - "npm-check-updates"
